language: node_js
node_js:
 - "4.4"

before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox